### ISSUE TITLE
[Feature request]Splash Screen with controls

### ISSUE THREAD

**Issue by ms-somanna** [NaBian/HandyControl#1002]
The inbuilt splashscreen feature of wpf provides for the display of a static bitmap image as splashscreen.
This disallows the use of dynamic controls such as progress bars and loading indicators.
So I request an implementation of A splash screen with controls including dynamic controls such as progress bars and loading indicators.

**Comment by ghost1372** [comment]
There is SplashWindow in the unofficial version, does it not meet your needs?
https://hosseini.ninja/handycontrol/persianToolkit/splashWindow/

**Comment by ms-somanna** [comment]
> There is SplashWindow in the unofficial version, does it not meet your needs?
> https://hosseini.ninja/handycontrol/persianToolkit/splashWindow/

I'll try it.

**Comment by ms-somanna** [comment]
> There is SplashWindow in the unofficial version, does it not meet your needs?
> https://hosseini.ninja/handycontrol/persianToolkit/splashWindow/

It's working but with one issue. The main window doesn't get focus (is minimised) once the splash window closes.
I've followed the docs to set up the splash window and I'm using visual studio 2022 preview 4.

**Comment by ghost1372** [comment]
> > There is SplashWindow in the unofficial version, does it not meet your needs?
> > https://hosseini.ninja/handycontrol/persianToolkit/splashWindow/
> 
> It's working but with one issue. The main window doesn't get focus (is minimised) once the splash window closes.
> I've followed the docs to set up the splash window and I'm using visual studio 2022 preview 4.

Can you attach a gif?

**Comment by ms-somanna** [comment]
Here
![splash_hides_main_window.gif](https://user-images.githubusercontent.com/32904377/135846745-68b3f954-566b-411d-a8e4-2dd00215eb01.gif)

**Comment by ghost1372** [comment]
This is not a splash screen problem and is a normal WPF behavior. also This is not minimized, By default, the MainWindow is displayed by **Show** Method (**Not ShowDialog**)
And because the splash screen is displayed before the mainWindow, the focus is on it.
You can use the P/Invok functions to get focus on the mainwindow or simply just set **Topmost=true**

with topmost

![asdasd](https://user-images.githubusercontent.com/9213496/135851928-810335e7-00e0-42b0-8e2f-3dd7c24b15e8.gif)
