### ISSUE TITLE
Button height doesn't work well in Designer View. [WPF]

### ISSUE THREAD

**Issue by JasperCalapini** [NaBian/HandyControl#1041]
The height of button do not adapt properly on designer that view. 
This works when I run the program _but not 'quite' in the designer view_. 

example:
```
<Grid>
<Button Height="auto" 
        VerticalAlignment="Stretch"
        HorizontalAlignment="Stretch"
        Text="Fill the Grid">
</Grid>
```

In the designer's view, only the `HorizontalAlignment="Stretch"` works. When I look at the properties on the `Button`, It says *Auto (30)*. When I set a constant height like `Height="10"` then set it back `Height="auto"`, The `VerticalAlignment="Stretch"` work. 

**Screenshots**

![handycontrol_button_bug_height_in_designer_view_ss1](https://user-images.githubusercontent.com/76414979/140595689-c51aff81-b6f7-4cac-8e68-908cf744b0f9.PNG)
![handycontrol_button_bug_height_in_designer_view_ss2](https://user-images.githubusercontent.com/76414979/140595691-e4ecce0f-cad6-4929-ac5e-100bc78708ab.PNG)
![handycontrol_button_bug_height_in_designer_view_ss3](https://user-images.githubusercontent.com/76414979/140595692-3027444f-337c-456f-b5d9-b5791239d831.PNG)
![handycontrol_button_bug_height_in_designer_view_ss4](https://user-images.githubusercontent.com/76414979/140595693-a4451a37-8852-4f06-8b6c-f95bfa49c1ad.PNG)

**Environment**
- .net : 4.8.04084
- IDE : Microsoft Visual Studio Community 2019
- Version : 16.11.5

**Additional context**
when you reopen the project/xaml, the _VerticalAlignment_ won't work again, height will again _auto(30)_ on the properties. Same if you increase the font size.

It works on Runtime but It would be nice if it works on designer view as well.
I am new to this wpf/programming and trying this wonderful

**Comment by 6outtaTen** [comment]
It is very common for weird issues to occur in the wpf designer. Most people would advise you not to use it, as it creates all sorts of problems. Often the app [appears normal in the designer but turns out horrible on runtime](https://stackoverflow.com/questions/19101525/wpf-window-layout-looks-different-from-vs-designer-when-running
) (or the other way around).
I would advise you to don't rely on the designer and write your own xaml code and use ["xaml hot reload"](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2022) to view changes.

This issue has got nothing to do with HandyControls but with the designer itself.

**Comment by NaBian** [comment]
> It is very common for weird issues to occur in the wpf designer. Most people would advise you not to use it, as it creates all sorts of problems. Often the app [appears normal in the designer but turns out horrible on runtime](https://stackoverflow.com/questions/19101525/wpf-window-layout-looks-different-from-vs-designer-when-running) (or the other way around). I would advise you to don't rely on the designer and write your own xaml code and use ["xaml hot reload"](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2022) to view changes.
> 
> This issue has got nothing to do with HandyControls but with the designer itself.
