### ISSUE TITLE
NumericUpDown设置ValueFormat=“X2”，报异常，原因是value为double类型

### ISSUE THREAD

**Issue by dzx815** [NaBian/HandyControl#1101]
**Describe the bug**
NumericUpDown设置ValueFormat=“X2”，报异常，原因是value为double类型

**To Reproduce**
1，xaml 添加<hc:NumericUpDown Value="11" ValueFormat="X2" Increment="10" Margin="81,10,129,225"/>
2，直接运行exe报错

**Expected behavior**
正常应该格式化成16进制数字显示在界面上，代码里可能要加一个判断，如果是格式化成16进制，就强制类型转换为int类型再格式化

**Screenshots**
![image](https://user-images.githubusercontent.com/15151459/149253911-0a6c4b7f-f77f-4789-b32a-125ae1a5a59c.png)

**Environment (please complete the following information):**
 - .net: [4.5]
 - IDE [vs2019]
 - Version [3.3.0.0]

**Additional context**
无

**Comment by Yopler** [comment]
Hi 🖐,

The behavior of your code is logic. HandyControl use the `ToString(string format)` function to format the text. 
Actually, if your try to do :
```cs
(3.52).ToString("X2");
```
You will get the exception : "FormatException: Invalid format specifier.".  C# is unable to format a `double `into a hexa format. 

However, the `X2` will never work using the NumericUpDown because the Value is cast as a double and you will always get the above exception. (see [NumericUpDown.cs#L247](https://github.com/HandyOrg/HandyControl/blob/master/src/Shared/HandyControl_Shared/Controls/Input/NumericUpDown.cs#L247))

So you just forward a bug, because we will never be able to format in Hexadecimal in NumericUpDown.

@NaBian @ghost1372 ,
One way to deal with this, is to add a property where we can specify the data Type.
Or Maybe ther is a way to get the Data type directly from the binding, because if the value is an `int `, `byte`, I think it will be interresting to format as HexaDecimal !

Hiope my answer will help 😊

**Comment by Yopler** [comment]
Here a link to the microsoft doc, to help you format your double : [Here](https://docs.microsoft.com/en-us/dotnet/api/system.double.tostring?view=net-6.0#System_Double_ToString_System_String_)

**Comment by dzx815** [comment]
Yeah，I know it, thank you for your reply.
I tried to change your source code, but I found that the values of this text box will be converted to the double value, resulting in errors, so I may need to write another such control myself.

Have a nice day!😊
